(()=>{
  const send=(message)=>new Promise(resolve=>chrome.runtime.sendMessage(message,resolve));
  const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  let busy=false;
  const msg=s=>({NOT_ACTIVATED:"Enter the license key provided by the administrator.",EXPIRED:"Your KFS access has expired. Activate another license to continue.",REVOKED:"This license has been revoked. Please contact support.",INVALID_KEY:"That license key is invalid.",ALREADY_ACTIVATED:"This license is already activated on another installation.",INSTALLATION_MISMATCH:"This license is bound to another installation.",NETWORK_UNAVAILABLE:"KFS could not contact the licensing server. Connect to the internet and try again.",RATE_LIMITED:"Too many licensing requests. Please wait and try again.",LEASE_EXPIRED:"KFS access could not be renewed. Please validate your license again.",LEASE_INVALID:"KFS access could not be verified. Please validate your license again."}[s]||"A valid KFS license is required.");
  function style(){if(document.getElementById("kfs-license-ui-style"))return;const s=document.createElement("style");s.id="kfs-license-ui-style";s.textContent=`#kfs-license-lock{position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:18px;background:#0b0d11;color:#fff;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;box-sizing:border-box}#kfs-license-lock[hidden]{display:none}#kfs-license-lock .card{width:min(360px,100%);background:#15181e;border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px;box-sizing:border-box;box-shadow:0 18px 50px rgba(0,0,0,.45)}#kfs-license-lock .brand{font-size:10px;letter-spacing:.15em;font-weight:800;opacity:.65;margin-bottom:10px}#kfs-license-lock h1{font-size:22px;line-height:1.2;margin:0 0 8px}#kfs-license-lock p{font-size:12px;line-height:1.45;color:#aeb4bf;margin:0 0 16px}#kfs-license-lock label{font-size:11px;font-weight:700;display:block;margin-bottom:6px}#kfs-license-lock input{width:100%;box-sizing:border-box;border:1px solid #3a404b;background:#0d1015;color:#fff;border-radius:9px;padding:11px 12px;outline:none;margin-bottom:8px}#kfs-license-lock button{width:100%;border:0;border-radius:9px;padding:11px 12px;margin-top:7px;font-weight:800;cursor:pointer}#kfs-license-lock button:disabled{opacity:.5;cursor:wait}#kfs-license-lock .primary{background:#fff;color:#111}#kfs-license-lock .result{min-height:18px;color:#ffb0b0;font-size:11px;margin-top:10px}#kfs-license-lock .note{font-size:10px;color:#737b87;margin:12px 0 0}`;document.head.appendChild(s)}
  function ensure(){style();let lock=document.getElementById("kfs-license-lock");if(lock)return lock;lock=document.createElement("div");lock.id="kfs-license-lock";lock.hidden=true;lock.innerHTML=`<section class="card" role="dialog" aria-modal="true" aria-label="KFS licensing"><div class="brand">KILLERS FROM SAGRES</div><h1 id="kfs-license-title">Activate KFS to continue</h1><p id="kfs-license-message">${esc(msg("NOT_ACTIVATED"))}</p><label for="kfs-license-key">License key</label><input id="kfs-license-key" maxlength="256" autocomplete="off" spellcheck="false" placeholder="Enter your license key"><button id="kfs-license-activate" class="primary" type="button">ACTIVATE LICENSE</button><div id="kfs-license-result" class="result" role="status" aria-live="polite"></div><p class="note">Your key is checked by the KFS licensing server. The key is not sent to the Lovable webpage.</p></section>`;document.body.appendChild(lock);lock.querySelector("#kfs-license-activate").addEventListener("click",()=>act());lock.querySelector("#kfs-license-key").addEventListener("keydown",e=>{if(e.key==="Enter")act()});return lock}
  function setLocked(status){const lock=ensure(),main=document.querySelector("main.shell");lock.hidden=false;if(main)main.style.visibility="hidden";const title=lock.querySelector("#kfs-license-title"),message=lock.querySelector("#kfs-license-message");if(title)title.textContent=status?.state==="EXPIRED"?"Your KFS access has expired":status?.state==="REVOKED"?"KFS license revoked":"Activate KFS to continue";if(message)message.textContent=status?.message||msg(status?.state)}
  function setUnlocked(){const lock=document.getElementById("kfs-license-lock"),main=document.querySelector("main.shell");if(lock)lock.hidden=true;if(main)main.style.visibility="visible"}
  async function check(){try{const state=await send({type:"KFS_LICENSE_STATUS"});if(state?.entitled===true){setUnlocked();return true}setLocked(state||{state:"NETWORK_UNAVAILABLE"});return false}catch(_){setLocked({state:"NETWORK_UNAVAILABLE"});return false}}
  async function act(){if(busy)return;busy=true;const lock=ensure(),key=lock.querySelector("#kfs-license-key").value.trim(),a=lock.querySelector("#kfs-license-activate"),r=lock.querySelector("#kfs-license-result");if(!key){r.textContent="Enter a license key.";busy=false;return}a.disabled=true;r.textContent="Verifying…";try{const result=await send({type:"KFS_LICENSE_ACTIVATE",license_key:key});if(result?.ok){const state=await send({type:"KFS_LICENSE_STATUS"});if(state?.entitled===true){window.location.reload();return}}r.textContent=result?.message||msg(result?.state)}catch(_){r.textContent=msg("NETWORK_UNAVAILABLE")}finally{busy=false;a.disabled=false}}
  function init(){void check();setInterval(()=>{if(!document.hidden)void check()},10000)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
