const KEYMASTER_ORIGIN="https://kfs-keymaster.lovable.app";
const API_BASE=`${KEYMASTER_ORIGIN}/api/public/v1`;
const REFRESH_ALARM="kfs-license-refresh";
const STATUS_CACHE_MS=10*1000;
const STORAGE_KEYS=["installation_id","license_key","license_plan","license_status","license_expires_at","lease_token","lease_expires_at","last_server_time","last_local_wall_time","last_validation_at","clock_rollback_detected"];
let installationPromise=null,refreshPromise=null,statusCache=null,statusCacheUntil=0,validationPromise=null;
const text=(v,max=2048)=>String(v??"").trim().slice(0,max);
const validInstallationId=v=>/^[A-Za-z0-9_-]{16,128}$/.test(String(v||""));
const now=()=>Date.now();
export async function getInstallationId(){if(installationPromise)return installationPromise;installationPromise=(async()=>{const current=await chrome.storage.local.get("installation_id");if(validInstallationId(current.installation_id))return current.installation_id;const id=crypto.randomUUID().replace(/-/g,"")+crypto.randomUUID().replace(/-/g,"");await chrome.storage.local.set({installation_id:id});return id})().finally(()=>{installationPromise=null});return installationPromise}
async function readState(){return chrome.storage.local.get(STORAGE_KEYS)}
function safeDate(v){const t=Date.parse(String(v||""));return Number.isFinite(t)?new Date(t).toISOString():""}
async function recordServerTime(serverTime){const t=Date.parse(String(serverTime||""));if(!Number.isFinite(t))return;const localMs=now(),previous=await chrome.storage.local.get("last_local_wall_time"),previousLocal=Number(previous.last_local_wall_time)||0;await chrome.storage.local.set({last_server_time:new Date(t).toISOString(),last_local_wall_time:localMs,clock_rollback_detected:previousLocal>0&&localMs<previousLocal-120000})}
async function post(path,payload){try{const response=await fetch(`${API_BASE}/${path}`,{method:"POST",headers:{"content-type":"application/json","x-kfs-client":"kfs-extension/1.9"},cache:"no-store",body:JSON.stringify(payload)});let body;try{body=await response.json()}catch(_){body={ok:false,code:"INVALID_RESPONSE",message:"The licensing server returned an invalid response."}}if(body?.server_time)await recordServerTime(body.server_time);return{http:response.status,body}}catch(error){return{network:true,error:String(error?.message||error)}}}
function normalizedLicense(body){const license=body?.license||{};return{plan:text(license.plan,64),status:text(license.status,64),expires_at:safeDate(license.expires_at),activated:license.activated===true,activated_at:safeDate(license.activated_at),server_time:safeDate(license.server_time||body?.server_time)}}
async function persistSuccess(body){const license=normalizedLicense(body),patch={license_plan:license.plan,license_status:license.status,license_expires_at:license.expires_at,last_validation_at:now(),clock_rollback_detected:false};const token=text(body?.lease_token,4096),leaseExpiry=safeDate(body?.lease_expires_at);if(token)patch.lease_token=token;if(leaseExpiry)patch.lease_expires_at=leaseExpiry;await chrome.storage.local.set(patch);await ensureRefreshAlarm();return license}
function mapFailure(body){const code=text(body?.code,64)||"LICENSING_ERROR";const state=code==="REVOKED"?"REVOKED":code==="EXPIRED"?"EXPIRED":code==="LEASE_EXPIRED"?"LEASE_EXPIRED":code==="ALREADY_ACTIVATED"?"ALREADY_ACTIVATED":code==="INSTALLATION_MISMATCH"?"INSTALLATION_MISMATCH":code==="DEVICE_LIMIT_REACHED"?"DEVICE_LIMIT_REACHED":code==="LEASE_INVALID"?"LEASE_INVALID":code==="RATE_LIMITED"?"RATE_LIMITED":code==="INVALID_KEY"?"INVALID_KEY":"NOT_ACTIVATED";return{ok:false,entitled:false,state,code,message:text(body?.message,512)||(code==="DEVICE_LIMIT_REACHED"?"Your license is already active on 4 devices. Deactivate one of your existing devices before activating this device.":code),server_time:safeDate(body?.server_time)}}
function entitlement(license){const status=license.status.toUpperCase(),serverNow=Date.parse(license.server_time),expiresAt=Date.parse(license.expires_at),shortLicenseExpired=license.plan==="twenty_minute"&&Number.isFinite(serverNow)&&Number.isFinite(expiresAt)&&serverNow>=expiresAt,entitled=status!=="REVOKED"&&status!=="EXPIRED"&&!shortLicenseExpired&&license.activated===true;return{ok:true,entitled,state:entitled?"LICENSE_ACTIVE":status==="EXPIRED"||shortLicenseExpired?"EXPIRED":"NOT_ACTIVATED",plan:license.plan,expires_at:license.expires_at,license,license_key_present:true}}
export async function activateLicense(licenseKey,clientVersion="1.9.0"){const key=text(licenseKey,256);if(!key)return{ok:false,state:"NOT_ACTIVATED",code:"INVALID_REQUEST",message:"Enter a license key."};const installation_id=await getInstallationId(),result=await post("activate",{license_key:key,installation_id,client_version:text(clientVersion,32)});if(result.network)return{ok:false,entitled:false,state:"NETWORK_UNAVAILABLE",message:"Could not contact the licensing server."};if(!result.body?.ok)return mapFailure(result.body);await chrome.storage.local.set({license_key:key,clock_rollback_detected:false});const license=await persistSuccess(result.body);statusCache=null;statusCacheUntil=0;return{ok:true,entitled:true,state:"LICENSE_ACTIVE",plan:license.plan,expires_at:license.expires_at,license,lease_expires_at:safeDate(result.body.lease_expires_at)}}
export async function deactivateLicense(clientVersion="1.9.0"){const state=await readState();if(!state.license_key)return{ok:true,state:"NOT_ACTIVATED"};const installation_id=await getInstallationId(),result=await post("deactivate",{license_key:text(state.license_key,256),installation_id,client_version:text(clientVersion,32)});if(result.network)return{ok:false,state:"NETWORK_UNAVAILABLE",message:"Could not contact the licensing server."};if(!result.body?.ok)return mapFailure(result.body);await chrome.storage.local.remove(["license_key","license_plan","license_status","license_expires_at","lease_token","lease_expires_at","last_validation_at","clock_rollback_detected"]);statusCache=null;statusCacheUntil=0;return{ok:true,state:"NOT_ACTIVATED"}}
export async function validateLicense(clientVersion="1.9.0"){if(validationPromise)return validationPromise;validationPromise=(async()=>{const state=await readState();if(!state.license_key)return{ok:true,entitled:false,state:"NOT_ACTIVATED",license_key_present:false};const installation_id=await getInstallationId(),payload={license_key:text(state.license_key,256),installation_id,client_version:text(clientVersion,32)};if(state.lease_token)payload.lease_token=text(state.lease_token,4096);const result=await post("validate",payload);if(result.network)return{ok:false,entitled:false,state:"NETWORK_UNAVAILABLE",message:"Could not validate the license with the server.",license_key_present:true};if(!result.body?.ok){const failure=mapFailure(result.body);await chrome.storage.local.set({license_status:failure.state,last_validation_at:now()});statusCache=failure;statusCacheUntil=now()+STATUS_CACHE_MS;return{...failure,license_key_present:true}}const license=await persistSuccess(result.body),value={...entitlement(license),lease_expires_at:safeDate(result.body.lease_expires_at),clock_rollback_detected:false};statusCache=value;statusCacheUntil=now()+STATUS_CACHE_MS;return value})();try{return await validationPromise}finally{validationPromise=null}}
export async function refreshLease(clientVersion="1.9.0"){if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{const state=await readState();if(!state.license_key||!state.lease_token)return state.license_key?validateLicense(clientVersion):{ok:true,entitled:false,state:"NOT_ACTIVATED"};const installation_id=await getInstallationId(),result=await post("lease",{lease_token:text(state.lease_token,4096),installation_id,client_version:text(clientVersion,32)});if(result.network)return{ok:false,entitled:false,state:"NETWORK_UNAVAILABLE",message:"Could not renew the license with the server."};if(!result.body?.ok){const failure=mapFailure(result.body);await chrome.storage.local.set({license_status:failure.state,last_validation_at:now()});statusCache=failure;statusCacheUntil=now()+STATUS_CACHE_MS;return failure}const license=await persistSuccess(result.body),value={...entitlement(license),lease_expires_at:safeDate(result.body.lease_expires_at)};statusCache=value;statusCacheUntil=now()+STATUS_CACHE_MS;return value})().finally(()=>{refreshPromise=null});return refreshPromise}
export async function getLicenseStatus(){if(statusCache&&now()<statusCacheUntil)return statusCache;const state=await readState();if(!state.license_key){const value={ok:true,entitled:false,state:"NOT_ACTIVATED",license_key_present:false,server_time:safeDate(state.last_server_time),clock_rollback_detected:state.clock_rollback_detected===true};statusCache=value;statusCacheUntil=now()+STATUS_CACHE_MS;return value}return validateLicense("1.9.0")}
export async function authorizePaidOperation(clientVersion="1.9.0"){if(statusCache&&now()<statusCacheUntil)return statusCache;return validateLicense(clientVersion)}
export async function ensureRefreshAlarm(){try{await chrome.alarms.create(REFRESH_ALARM,{delayInMinutes:240,periodInMinutes:240})}catch(_){} }
export async function initializeLicensing(){await getInstallationId();await ensureRefreshAlarm();const state=await readState();if(state.license_key&&state.lease_token)void refreshLease()}
export const LICENSE_REFRESH_ALARM=REFRESH_ALARM;
export const LICENSE_LEASE_MAX_MS=6*60*60*1000;
// Kept only so an older service-worker import cannot break after upgrade. It never grants access.
export async function startTrial(){return{ok:false,entitled:false,state:"NOT_ACTIVATED",code:"FEATURE_DISABLED",message:"Free trials are no longer available. Enter a license key."}}
