(()=>{
  if(window.__KFS_LICENSE_GATE_V4__)return;
  window.__KFS_LICENSE_GATE_V4__=1;
  const send=message=>new Promise(resolve=>chrome.runtime.sendMessage(message,resolve));
  let overlay=null,shown=false,timer=null;
  const messageFor=s=>({NOT_ACTIVATED:"Activate your KFS license from the extension popup to continue.",EXPIRED:"Your KFS access has expired. Activate another license from the extension popup.",REVOKED:"This license has been revoked. Please contact support.",ALREADY_ACTIVATED:"This license is already active on another installation.",INSTALLATION_MISMATCH:"This license is bound to another installation.",NETWORK_UNAVAILABLE:"KFS could not verify your access. Open the extension popup and connect to the internet."}[s]||"A valid KFS license is required.");
  function remove(){overlay?.remove();overlay=null;shown=false;document.documentElement.classList.remove("kfs-license-locked");if(timer){clearInterval(timer);timer=null}}
  function styles(){if(document.getElementById("kfs-license-gate-style"))return;const s=document.createElement("style");s.id="kfs-license-gate-style";s.textContent=`html.kfs-license-locked body>*:not(#kfs-license-gate-overlay):not(#kfs-startup-gate){pointer-events:none!important}.kfs-license-gate-overlay{position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(8,10,14,.94);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}.kfs-license-gate-card{width:min(520px,calc(100vw - 32px));box-sizing:border-box;background:#12151b;border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:28px;box-shadow:0 24px 80px rgba(0,0,0,.5);text-align:center}.kfs-license-gate-brand{font-size:11px;letter-spacing:.16em;font-weight:800;opacity:.72;margin-bottom:12px}.kfs-license-gate-card h1{margin:0 0 10px;font-size:28px;line-height:1.15}.kfs-license-gate-card p{margin:0 0 20px;color:#b9bec8;line-height:1.5}.kfs-license-primary{display:block;width:100%;box-sizing:border-box;padding:13px 14px;border:0;border-radius:10px;background:#fff;color:#101216;font-weight:800;cursor:pointer}.kfs-license-note{margin-top:14px!important;margin-bottom:0!important;font-size:11px!important;color:#858c98!important}`;document.documentElement.appendChild(s)}
  async function openExtension(){try{const result=await send({type:"KFS_OPEN_LICENSE_UI"});if(!result?.ok){const m=document.getElementById("kfs-lg-message");if(m)m.textContent=result?.message||"Não foi possível abrir a tela de licença."}}catch(_){const m=document.getElementById("kfs-lg-message");if(m)m.textContent="Não foi possível abrir a tela de licença. Abra a extensão manualmente."}}
  function show(status){if(overlay){update(status);return}shown=true;styles();document.documentElement.classList.add("kfs-license-locked");overlay=document.createElement("div");overlay.id="kfs-license-gate-overlay";overlay.className="kfs-license-gate-overlay";overlay.innerHTML=`<section class="kfs-license-gate-card" role="dialog" aria-modal="true" aria-label="KFS license"><div class="kfs-license-gate-brand">KILLERS FROM SAGRES</div><h1 id="kfs-lg-title">Activate KFS to continue</h1><p id="kfs-lg-message">${messageFor(status?.state)}</p><button class="kfs-license-primary" type="button" id="kfs-open-extension">OPEN THE KFS EXTENSION</button><p class="kfs-license-note">Use the extension popup to enter the license key provided by the administrator. The webpage never receives your license key.</p></section>`;(document.body||document.documentElement).appendChild(overlay);overlay.querySelector("#kfs-open-extension")?.addEventListener("click",openExtension)}
  function update(status){const t=document.getElementById("kfs-lg-title"),m=document.getElementById("kfs-lg-message");if(t)t.textContent=status?.state==="EXPIRED"?"Your KFS access has expired":status?.state==="REVOKED"?"KFS license revoked":"Activate KFS to continue";if(m)m.textContent=status?.message||messageFor(status?.state)}
  async function check(){try{const status=await send({type:"KFS_LICENSE_STATUS"});if(status?.entitled){if(shown)remove();return true}show(status);return false}catch(_){show({state:"NETWORK_UNAVAILABLE"});return false}}
  function boot(){void check();timer=setInterval(()=>{if(!document.hidden)void check()},10000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)void check()});if(chrome?.storage?.local?.onChanged){chrome.storage.local.onChanged.addListener((changes,area)=>{if(area!=="local")return;const relevant=["license_key","license_plan","license_status","lease_token","lease_expires_at","license_expires_at","last_validation_at","last_server_time"];if(relevant.some(key=>key in changes))void check();})}}
  boot();
})();