(()=>{
  if(window.__KFS_LICENSE_GATE_V4__)return;
  window.__KFS_LICENSE_GATE_V4__=1;
  const send=message=>new Promise(resolve=>chrome.runtime.sendMessage(message,resolve));
  let overlay=null,shown=false,timer=null;
  const messageFor=s=>({NOT_ACTIVATED:"Activate your KFS license from the extension popup to continue.",EXPIRED:"Your KFS access has expired. Activate another license from the extension popup.",REVOKED:"This license has been revoked. Please contact support.",ALREADY_ACTIVATED:"This license is already active on another installation.",INSTALLATION_MISMATCH:"This license is bound to another installation.",NETWORK_UNAVAILABLE:"KFS could not verify your access. Open the extension popup and connect to the internet."}[s]||"A valid KFS license is required.");
  function remove(){overlay?.remove();overlay=null;shown=false;document.documentElement.classList.remove("kfs-license-locked");if(timer){clearInterval(timer);timer=null}}
  function styles(){if(document.getElementById("kfs-license-gate-style"))return;const s=document.createElement("style");s.id="kfs-license-gate-style";s.textContent=`html.kfs-license-locked body>*:not(#kfs-license-gate-overlay):not(#kfs-startup-gate){pointer-events:none!important}.kfs-license-gate-overlay{position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(8,10,14,.94);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}.kfs-license-frame{width:min(420px,calc(100vw - 32px));height:min(600px,calc(100vh - 32px));border:0;border-radius:18px;background:#0b0d11;box-shadow:0 24px 80px rgba(0,0,0,.5);visibility:hidden}.kfs-license-frame.is-ready{visibility:visible}`;document.documentElement.appendChild(s)}
  function show(status){if(window.__KFS_STARTUP_GATE_ACTIVE__){window.__KFS_PENDING_LICENSE_STATUS__=status;return}if(overlay){update(status);return}shown=true;styles();document.documentElement.classList.add("kfs-license-locked");overlay=document.createElement("div");overlay.id="kfs-license-gate-overlay";overlay.className="kfs-license-gate-overlay";overlay.innerHTML=`<iframe class="kfs-license-frame" title="KFS license activation" src="${chrome.runtime.getURL("license.html")}"></iframe>`;const frame=overlay.querySelector(".kfs-license-frame");window.addEventListener("message",event=>{if(event.source===frame.contentWindow&&event.data?.type==="KFS_LICENSE_UI_READY")frame.classList.add("is-ready")},{once:true});(document.body||document.documentElement).appendChild(overlay)}
  function update(status){const t=document.getElementById("kfs-lg-title"),m=document.getElementById("kfs-lg-message");if(t)t.textContent=status?.state==="EXPIRED"?"Your KFS access has expired":status?.state==="REVOKED"?"KFS license revoked":"Activate KFS to continue";if(m)m.textContent=status?.message||messageFor(status?.state)}
  async function check(){try{const status=await send({type:"KFS_LICENSE_STATUS"});if(status?.entitled){if(shown)remove();return true}show(status);return false}catch(_){show({state:"NETWORK_UNAVAILABLE"});return false}}
  function boot(){void check();timer=setInterval(()=>{if(!document.hidden)void check()},10000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)void check()});if(chrome?.storage?.local?.onChanged){chrome.storage.local.onChanged.addListener((changes,area)=>{if(area!=="local")return;const relevant=["license_key","license_plan","license_status","lease_token","lease_expires_at","license_expires_at","last_validation_at","last_server_time"];if(relevant.some(key=>key in changes))void check();})}}
  boot();
})();